# Generated by Selenium IDE
import os
import base64
from selenium import webdriver
from selenium.webdriver import ChromeOptions
from selenium.webdriver.common.by import By

class Scrapper():
  def __init__(self):
    options = ChromeOptions()
    options.add_argument("--no-sandbox")
    options.add_argument("--headless")
    options.add_argument("--disable-dev-shm-usage")
    key = os.environ['BC_KEY']
    key = bytes(key, "utf-8")
    decoded_key = base64.b64decode(key)
    decoded_key = str(decoded_key, "utf-8")
    split_key = decoded_key.split(":")
    self.user = split_key[0]
    self.passwd = split_key[1]
    self.url = os.environ['BC_URL']
    self.driver = webdriver.Chrome(chrome_options=options)
  
  def run(self):
    self.driver.get(self.url)

    self.driver.find_element(By.ID, "usuario").send_keys(self.user)
    self.driver.find_element(By.ID, "contrasena").send_keys(self.passwd)
    self.driver.find_element(By.NAME, "b_acceder").click()

    self.driver.find_element(By.CSS_SELECTOR, ".c_c_fondo_claro:nth-child(1) .accede_his2 > img").click()

    meal = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(9) > .c_c_texto").text
    nap = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(12) .c_c_texto").text
    dummy = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(15) .c_c_texto").text

    f = lambda x: x.split(':')[1]

    meal = f(meal)
    nap = f(nap)
    dummy = f(dummy)

    self.driver.quit()

    return {
      "meal": meal,
      "nap": nap,
      "dummy": dummy
    }
